services:
    server:
        build: .
        init: true
        ports:
            - "3000:3000"
        volumes:
            - cc-server-scripts:/home/node/server/scripts

volumes:
    cc-server-scripts: {}
